package simpledb;

import java.util.*;
import java.util.concurrent.ConcurrentHashMap;

/**
 * The Join operator implements the relational join operation.
 */
public class HashEquiJoin extends Operator {

    private static final long serialVersionUID = 1L;

    private final JoinPredicate p;
    private final DbIterator child1, child2;
    private final Map<Integer, List<Tuple>> rightHash;

    /**
     * Constructor. Accepts to children to join and the predicate to join them
     * on
     *
     * @param p      The predicate to use to join the children
     * @param child1 Iterator for the left(outer) relation to join
     * @param child2 Iterator for the right(inner) relation to join
     */
    public HashEquiJoin(JoinPredicate p, DbIterator child1, DbIterator child2) {
        this.p = p;
        this.child1 = child1;
        this.child2 = child2;
        this.rightHash = new HashMap<>();
    }

    public JoinPredicate getJoinPredicate() {
        return p;
    }

    public TupleDesc getTupleDesc() {
        return TupleDesc.merge(child1.getTupleDesc(), child2.getTupleDesc());
    }

    public String getJoinField1Name() {
        return child1.getTupleDesc().getFieldName(p.getField1());
    }

    public String getJoinField2Name() {
        return child2.getTupleDesc().getFieldName(p.getField2());
    }

    private void initializeRightHash() throws TransactionAbortedException, DbException {
        while (child2.hasNext()) {
            Tuple cur = child2.next();
            rightHash.computeIfAbsent(cur.getField(p.getField2()).hashCode(), (k) -> new ArrayList<>()).add(cur);
        }
    }

    public void open() throws DbException, NoSuchElementException,
            TransactionAbortedException {
        super.open();
        child1.open();
        child2.open();
        initializeRightHash();
        child2.close();
    }

    public void close() {
        super.close();
        child1.close();
    }

    public void rewind() throws DbException, TransactionAbortedException {
        child1.rewind();
        t1 = null;
        listIt = null;
    }

    private Tuple t1 = null;

    transient Iterator<Tuple> listIt = null;

    /**
     * Returns the next tuple generated by the join, or null if there are no
     * more tuples. Logically, this is the next tuple in r1 cross r2 that
     * satisfies the join predicate. There are many possible implementations;
     * the simplest is a nested loops join.
     * <p>
     * Note that the tuples returned from this particular implementation of Join
     * are simply the concatenation of joining tuples from the left and right
     * relation. Therefore, there will be two copies of the join attribute in
     * the results. (Removing such duplicate columns can be done with an
     * additional projection operator if needed.)
     * <p>
     * For example, if one tuple is {1,2,3} and the other tuple is {1,5,6},
     * joined on equality of the first column, then this returns {1,2,3,1,5,6}.
     *
     * @return The next matching tuple.
     * @see JoinPredicate#filter
     */
    protected Tuple fetchNext() throws TransactionAbortedException, DbException {
        while (true) {
            if (listIt != null && listIt.hasNext()) {
                Tuple t2 = listIt.next();
                Tuple ret = new Tuple(getTupleDesc());
                for (int i = 0; i < t1.getTupleDesc().numFields(); i++)
                    ret.setField(i, t1.getField(i));
                for (int i = t1.getTupleDesc().numFields(), j = 0; j < t2.getTupleDesc().numFields(); i++, j++)
                    ret.setField(i, t2.getField(j));
                return ret;
            }
            if (!child1.hasNext()) return null;
            t1 = child1.next();
            List<Tuple> list = rightHash.get(t1.getField(p.getField1()).hashCode());
            if (list == null) listIt = null;
            else listIt = list.iterator();
        }
    }

    @Override
    public DbIterator[] getChildren() {
        DbIterator[] ret = new DbIterator[2];
        setChildren(ret);
        return ret;
    }

    @Override
    public void setChildren(DbIterator[] children) {
        children[0] = child1;
        children[1] = child2;
    }

}
